#!/bin/bash

#IAM認証設定
export AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}"
export AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}"
export AWS_DEFAULT_REGION="${AWS_DEFAULT_REGION}"

#アクション権限 設定対象
export TARGET_IAM_POLICY_ARN="${TARGET_IAM_POLICY_ARN}"
